### ISSUE TITLE
Conexión a base de datos 

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipo-j-a-k#1]
[
[CONEXION A LA BASE DE DATOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipo-j-a-k/files/15445654/CONEXION.A.LA.BASE.DE.DATOS.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 20
